language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t staskosatkin/react-test -f ./client/dev.dockerfile ./client
script:
  - docker run -e CI=true staskosatkin/react-test npm test

after_success:
  - docker build -t staskosatkin/multi-client ./client
  - docker build -t staskosatkin/multi-nginx ./nginx
  - docker build -t staskosatkin/multi-server ./server
  - docker build -t staskosatkin/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push staskosatkin/multi-client
  - docker push staskosatkin/multi-nginx
  - docker push staskosatkin/multi-server
  - docker push staskosatkin/multi-worker

