version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: dev.dockerfile
    ports:
      - '3050:80'
  api:
    depends_on:
      - redis
      - postgres
    build:
      context: ./server
      dockerfile: dev.dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
  client:
    depends_on:
      - api
    stdin_open: true
    build:
      context: ./client
      dockerfile: dev.dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    depends_on:
      - redis
    build:
      context: ./worker
      dockerfile: dev.dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
